name: Release
on:
  release:
    types:
      - created

jobs:
  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: Install Yarn
      run: npm install yarn
    - name: install dependencies
      run: npx yarn
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
