name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
        cache: 'yarn'
    - name: Set Path for candle and light
      run: $GITHUB_PATH=$GITHUB_PATH + ";" + $((Get-ChildItem "C:\Program Files (x86)\" | Where-Object { $_.PSIsContainer -and $_.Name.StartsWith("WiX")}).FullName + "\bin")
    - name: install
      run: yarn install
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish
